import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQVVqssk1aMPh5cgJi2a3XAqFJ2_cOXPc',
    appId: '1:955408721623:web:e78c39e6801db32545b292',
    messagingSenderId: '955408721623',
    projectId: 'apisavana-bf-226',
    authDomain: 'apisavana-bf-226.firebaseapp.com',
    storageBucket: 'apisavana-bf-226.firebasestorage.app',
    measurementId: 'G-NH4D0Q9NTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQVVqssk1aMPh5cgJi2a3XAqFJ2_cOXPc',
    appId: '1:955408721623:android:e78c39e6801db32545b292',
    messagingSenderId: '955408721623',
    projectId: 'apisavana-bf-226',
    storageBucket: 'apisavana-bf-226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQVVqssk1aMPh5cgJi2a3XAqFJ2_cOXPc',
    appId: '1:955408721623:ios:e78c39e6801db32545b292',
    messagingSenderId: '955408721623',
    projectId: 'apisavana-bf-226',
    storageBucket: 'apisavana-bf-226.firebasestorage.app',
    iosBundleId: 'com.example.apisavanaGestion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQVVqssk1aMPh5cgJi2a3XAqFJ2_cOXPc',
    appId: '1:955408721623:ios:e78c39e6801db32545b292',
    messagingSenderId: '955408721623',
    projectId: 'apisavana-bf-226',
    storageBucket: 'apisavana-bf-226.firebasestorage.app',
    iosBundleId: 'com.example.apisavanaGestion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQVVqssk1aMPh5cgJi2a3XAqFJ2_cOXPc',
    appId: '1:955408721623:web:e78c39e6801db32545b292',
    messagingSenderId: '955408721623',
    projectId: 'apisavana-bf-226',
    authDomain: 'apisavana-bf-226.firebaseapp.com',
    storageBucket: 'apisavana-bf-226.firebasestorage.app',
    measurementId: 'G-NH4D0Q9NTS',
  );
}